/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[ApplicationRoleHistoryLog]
(
[ApplicationRoleId] [int] NOT NULL,
[ApplicationId] [int] NOT NULL,
[RoleId] [int] NOT NULL,
[NavigationId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_ApplicationRoleHistoryLog] ON [dbo].[ApplicationRoleHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[ApplicationRole]
(
[ApplicationRoleId] [int] NOT NULL IDENTITY(1, 1),
[ApplicationId] [int] NOT NULL,
[RoleId] [int] NOT NULL,
[NavigationId] [int] NOT NULL CONSTRAINT [DF__Applicati__Navig__21D92E4A] DEFAULT ((1)),
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_ApplicationRole_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFApplicationRoleStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFApplicationRoleEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_ApplicationRole] PRIMARY KEY CLUSTERED ([ApplicationRoleId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[ApplicationRoleHistoryLog])
)
GO
ALTER TABLE [dbo].[ApplicationRole] ADD CONSTRAINT [UKApplicationRoleApplicationIdRoleId] UNIQUE NONCLUSTERED ([ApplicationId], [RoleId])
GO
ALTER TABLE [dbo].[ApplicationRole] ADD CONSTRAINT [FK_ApplicationRole_Application] FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[Application] ([ApplicationId])
GO
ALTER TABLE [dbo].[ApplicationRole] ADD CONSTRAINT [FK_ApplicationRole_Navigation] FOREIGN KEY ([NavigationId]) REFERENCES [dbo].[Navigation] ([NavigationId])
GO
ALTER TABLE [dbo].[ApplicationRole] ADD CONSTRAINT [FK_ApplicationRole_Role] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Role] ([RoleId])
GO
