/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[ApplicationRoleNavigationHistoryLog]
(
[ApplicationRoleNavigationId] [int] NOT NULL,
[ApplicationRoleId] [int] NOT NULL,
[NavigationId] [int] NOT NULL,
[DisplayOrder] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_ApplicationRoleNavigationHistoryLog] ON [dbo].[ApplicationRoleNavigationHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[ApplicationRoleNavigation]
(
[ApplicationRoleNavigationId] [int] NOT NULL IDENTITY(1, 1),
[ApplicationRoleId] [int] NOT NULL,
[NavigationId] [int] NOT NULL,
[DisplayOrder] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_ApplicationRoleNavigation_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFApplicationRoleNavigationStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFApplicationRoleNavigationEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_ApplicationRoleNavigation] PRIMARY KEY CLUSTERED ([ApplicationRoleNavigationId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[ApplicationRoleNavigationHistoryLog])
)
GO
ALTER TABLE [dbo].[ApplicationRoleNavigation] ADD CONSTRAINT [UkApplicationRoleNavigationApplicationRoleIdNavigationId] UNIQUE NONCLUSTERED ([ApplicationRoleId], [NavigationId])
GO
ALTER TABLE [dbo].[ApplicationRoleNavigation] ADD CONSTRAINT [FK_ApplicationRoleNavigation_ApplicationRole] FOREIGN KEY ([ApplicationRoleId]) REFERENCES [dbo].[ApplicationRole] ([ApplicationRoleId])
GO
ALTER TABLE [dbo].[ApplicationRoleNavigation] ADD CONSTRAINT [FK_ApplicationRoleNavigation_Navigation] FOREIGN KEY ([NavigationId]) REFERENCES [dbo].[Navigation] ([NavigationId])
GO
