/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[ApplicationRoleNavigationActionHistoryLog]
(
[ApplicationRoleNavigationActionId] [int] NOT NULL,
[ApplicationRoleId] [int] NOT NULL,
[NavigationActionId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_ApplicationRoleNavigationActionHistoryLog] ON [dbo].[ApplicationRoleNavigationActionHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[ApplicationRoleNavigationAction]
(
[ApplicationRoleNavigationActionId] [int] NOT NULL IDENTITY(1, 1),
[ApplicationRoleId] [int] NOT NULL,
[NavigationActionId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_ApplicationRoleNavigationAction_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFApplicationRoleNavigationActionStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFApplicationRoleNavigationActionEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_ApplicationRoleNavigationAction] PRIMARY KEY CLUSTERED ([ApplicationRoleNavigationActionId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[ApplicationRoleNavigationActionHistoryLog])
)
GO
ALTER TABLE [dbo].[ApplicationRoleNavigationAction] ADD CONSTRAINT [UkApplicationRoleNavigationActionApplicationRoleIdNavigationActionId] UNIQUE NONCLUSTERED ([ApplicationRoleId], [NavigationActionId])
GO
ALTER TABLE [dbo].[ApplicationRoleNavigationAction] ADD CONSTRAINT [FK_ApplicationRoleNavigationAction_ApplicationRole] FOREIGN KEY ([ApplicationRoleId]) REFERENCES [dbo].[ApplicationRole] ([ApplicationRoleId])
GO
ALTER TABLE [dbo].[ApplicationRoleNavigationAction] ADD CONSTRAINT [FK_ApplicationRoleNavigationAction_NavigationAction] FOREIGN KEY ([NavigationActionId]) REFERENCES [dbo].[NavigationAction] ([NavigationActionId])
GO
