/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[CultureHistoryLog]
(
[CultureId] [int] NOT NULL,
[CultureCode] [varchar] (5) NOT NULL,
[Language] [nvarchar] (25) NOT NULL,
[SortOrder] [tinyint] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_CultureHistoryLog] ON [dbo].[CultureHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[Culture]
(
[CultureId] [int] NOT NULL IDENTITY(1, 1),
[CultureCode] [varchar] (5) NOT NULL,
[Language] [nvarchar] (25) NOT NULL,
[SortOrder] [tinyint] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_Culture_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFCultureStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFCultureEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_Culture] PRIMARY KEY CLUSTERED ([CultureId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[CultureHistoryLog])
)
GO
ALTER TABLE [dbo].[Culture] ADD CONSTRAINT [UkCultureCultureCode] UNIQUE NONCLUSTERED ([CultureCode])
GO
