/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[ListItemCategoryHistoryLog]
(
[ListItemCategoryId] [int] NOT NULL,
[IsSystem] [bit] NOT NULL,
[Category] [varchar] (50) NOT NULL,
[Description] [varchar] (200) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_ListItemCategoryHistoryLog] ON [dbo].[ListItemCategoryHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[ListItemCategory]
(
[ListItemCategoryId] [int] NOT NULL IDENTITY(1, 1),
[IsSystem] [bit] NOT NULL CONSTRAINT [DF_ListItemCategory_IsSystem] DEFAULT ((0)),
[Category] [varchar] (50) NOT NULL,
[Description] [varchar] (200) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_ListItemCategory_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFListItemCategoryStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFListItemCategoryEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_ListItemCategory] PRIMARY KEY CLUSTERED ([ListItemCategoryId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[ListItemCategoryHistoryLog])
)
GO
ALTER TABLE [dbo].[ListItemCategory] ADD CONSTRAINT [UkListItemCategoryCategory] UNIQUE NONCLUSTERED ([Category])
GO
