/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[NavigationNodeHistoryLog]
(
[NavigationNodeId] [int] NOT NULL,
[NavigationId] [int] NOT NULL,
[NodeId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_NavigationNodeHistoryLog] ON [dbo].[NavigationNodeHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[NavigationNode]
(
[NavigationNodeId] [int] NOT NULL IDENTITY(1, 1),
[NavigationId] [int] NOT NULL,
[NodeId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_NavigationNode_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFNavigationNodeStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFNavigationNodeEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_NavigationNode] PRIMARY KEY CLUSTERED ([NavigationNodeId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[NavigationNodeHistoryLog])
)
GO
ALTER TABLE [dbo].[NavigationNode] ADD CONSTRAINT [FK_NavigationNode_Navigation] FOREIGN KEY ([NavigationId]) REFERENCES [dbo].[Navigation] ([NavigationId])
GO
ALTER TABLE [dbo].[NavigationNode] ADD CONSTRAINT [FK_NavigationNode_Node] FOREIGN KEY ([NodeId]) REFERENCES [dbo].[Node] ([NodeId])
GO
