/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[NavigationActionHistoryLog]
(
[NavigationActionId] [int] NOT NULL,
[NavigationId] [int] NOT NULL,
[Action] [nvarchar] (50) NOT NULL,
[Description] [nvarchar] (200) NOT NULL,
[NavigationActionTypeListItemId] [int] NOT NULL,
[ResourceId] [int] NOT NULL,
[Icon] [varchar] (25) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_NavigationActionHistoryLog] ON [dbo].[NavigationActionHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[NavigationAction]
(
[NavigationActionId] [int] NOT NULL IDENTITY(1, 1),
[NavigationId] [int] NOT NULL,
[Action] [nvarchar] (50) NOT NULL,
[Description] [nvarchar] (200) NOT NULL,
[NavigationActionTypeListItemId] [int] NOT NULL,
[ResourceId] [int] NOT NULL,
[Icon] [varchar] (25) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_NavigationAction_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFNavigationActionStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFNavigationActionEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_NavigationAction] PRIMARY KEY CLUSTERED ([NavigationActionId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[NavigationActionHistoryLog])
)
GO
ALTER TABLE [dbo].[NavigationAction] ADD CONSTRAINT [UkNavigationActionNavigationIdAction] UNIQUE NONCLUSTERED ([NavigationId], [Action])
GO
ALTER TABLE [dbo].[NavigationAction] ADD CONSTRAINT [FK_NavigationAction_Navigation] FOREIGN KEY ([NavigationId]) REFERENCES [dbo].[Navigation] ([NavigationId])
GO
