/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[NavigationHistoryLog]
(
[NavigationId] [int] NOT NULL,
[Navigation] [nvarchar] (100) NOT NULL,
[URL] [varchar] (50) NOT NULL,
[IsExternal] [bit] NOT NULL,
[NavigationTypeListItemId] [int] NOT NULL,
[ParentNavigationId] [int] NULL,
[RootNavigationId] [int] NULL,
[Icon] [varchar] (25) NULL,
[DisplayOrder] [int] NOT NULL,
[ResourceId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_NavigationHistoryLog] ON [dbo].[NavigationHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[Navigation]
(
[NavigationId] [int] NOT NULL IDENTITY(1, 1),
[Navigation] [nvarchar] (100) NOT NULL,
[URL] [varchar] (50) NOT NULL CONSTRAINT [DF_Navigation_URL] DEFAULT ('/home'),
[IsExternal] [bit] NOT NULL CONSTRAINT [DF_Navigation_IsExternal] DEFAULT ((1)),
[NavigationTypeListItemId] [int] NOT NULL,
[ParentNavigationId] [int] NULL,
[RootNavigationId] [int] NULL,
[Icon] [varchar] (25) NULL,
[DisplayOrder] [int] NOT NULL,
[ResourceId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_Navigation_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFNavigationStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFNavigationEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_Navigation] PRIMARY KEY CLUSTERED ([NavigationId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[NavigationHistoryLog])
)
GO
ALTER TABLE [dbo].[Navigation] ADD CONSTRAINT [UkNavigationURL] UNIQUE NONCLUSTERED ([URL])
GO
ALTER TABLE [dbo].[Navigation] ADD CONSTRAINT [FK_Navigation_Navigation] FOREIGN KEY ([RootNavigationId]) REFERENCES [dbo].[Navigation] ([NavigationId])
GO
ALTER TABLE [dbo].[Navigation] ADD CONSTRAINT [FK_Navigation_Navigation1] FOREIGN KEY ([ParentNavigationId]) REFERENCES [dbo].[Navigation] ([NavigationId])
GO
ALTER TABLE [dbo].[Navigation] ADD CONSTRAINT [FK_Navigation_Resource] FOREIGN KEY ([ResourceId]) REFERENCES [dbo].[Resource] ([ResourceId])
GO
