/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[NodeHistoryLog]
(
[NodeId] [int] NOT NULL,
[NodeTypeId] [int] NOT NULL,
[ParentNodeId] [int] NULL,
[RootNodeId] [int] NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_NodeHistoryLog] ON [dbo].[NodeHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[Node]
(
[NodeId] [int] NOT NULL IDENTITY(1, 1),
[NodeTypeId] [int] NOT NULL,
[ParentNodeId] [int] NULL,
[RootNodeId] [int] NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_Node_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFNodeStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFNodeEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_Node] PRIMARY KEY CLUSTERED ([NodeId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[NodeHistoryLog])
)
GO
ALTER TABLE [dbo].[Node] ADD CONSTRAINT [FK_Node_Node] FOREIGN KEY ([ParentNodeId]) REFERENCES [dbo].[Node] ([NodeId])
GO
ALTER TABLE [dbo].[Node] ADD CONSTRAINT [FK_Node_Node1] FOREIGN KEY ([RootNodeId]) REFERENCES [dbo].[Node] ([NodeId])
GO
ALTER TABLE [dbo].[Node] ADD CONSTRAINT [FK_Node_NodeType] FOREIGN KEY ([NodeTypeId]) REFERENCES [dbo].[NodeType] ([NodeTypeId])
GO
