/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[NodeTypeHistoryLog]
(
[NodeTypeId] [int] NOT NULL,
[NodeType] [varchar] (25) NOT NULL,
[ParentNodeTypeId] [int] NULL,
[RootNodeTypeId] [int] NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_NodeTypeHistoryLog] ON [dbo].[NodeTypeHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[NodeType]
(
[NodeTypeId] [int] NOT NULL IDENTITY(1, 1),
[NodeType] [varchar] (25) NOT NULL,
[ParentNodeTypeId] [int] NULL,
[RootNodeTypeId] [int] NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_NodeType_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFNodeTypeStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFNodeTypeEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_NodeType] PRIMARY KEY CLUSTERED ([NodeTypeId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[NodeTypeHistoryLog])
)
GO
ALTER TABLE [dbo].[NodeType] ADD CONSTRAINT [UkNodeTypeNodeType] UNIQUE NONCLUSTERED ([NodeType])
GO
ALTER TABLE [dbo].[NodeType] ADD CONSTRAINT [FK_NodeType_NodeType] FOREIGN KEY ([RootNodeTypeId]) REFERENCES [dbo].[NodeType] ([NodeTypeId])
GO
ALTER TABLE [dbo].[NodeType] ADD CONSTRAINT [FK_NodeType_NodeType1] FOREIGN KEY ([ParentNodeTypeId]) REFERENCES [dbo].[NodeType] ([NodeTypeId])
GO
