/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[OfficeHistoryLog]
(
[OfficeId] [int] NOT NULL,
[OrganizationId] [int] NOT NULL,
[Office] [nvarchar] (100) NOT NULL,
[OfficeTypeListItemId] [int] NOT NULL,
[NodeId] [int] NOT NULL,
[StatusListItemId] [int] NOT NULL,
[GLCode] [varchar] (25) NOT NULL,
[RootOfficeId] [int] NULL,
[ParentOfficeId] [int] NULL,
[IsIncludeInPortal] [bit] NOT NULL,
[BackOfficeId] [int] NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[ReferenceId] [varchar] (50) NULL,
[ReferenceNote] [varchar] (100) NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL,
[PortalName] [nvarchar] (100) NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_OfficeHistoryLog] ON [dbo].[OfficeHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[Office]
(
[OfficeId] [int] NOT NULL IDENTITY(1, 1),
[OrganizationId] [int] NOT NULL,
[Office] [nvarchar] (100) NOT NULL,
[OfficeTypeListItemId] [int] NOT NULL,
[NodeId] [int] NOT NULL,
[StatusListItemId] [int] NOT NULL,
[GLCode] [varchar] (25) NOT NULL CONSTRAINT [DF_Office_GLCode] DEFAULT ('000'),
[RootOfficeId] [int] NULL,
[ParentOfficeId] [int] NULL,
[IsIncludeInPortal] [bit] NOT NULL CONSTRAINT [DF_Office_IsIncludeInPortal] DEFAULT ((1)),
[BackOfficeId] [int] NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_Office_InsertDate] DEFAULT (getdate()),
[ReferenceId] [varchar] (50) NULL,
[ReferenceNote] [varchar] (100) NULL,
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFOfficeStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFOfficeEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
[PortalName] [nvarchar] (100) NOT NULL CONSTRAINT [DF__Office__PortalNa__38B5379A] DEFAULT (''),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_Office] PRIMARY KEY CLUSTERED ([OfficeId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[OfficeHistoryLog])
)
GO
ALTER TABLE [dbo].[Office] ADD CONSTRAINT [UKOfficeOrganizationIdOffice] UNIQUE NONCLUSTERED ([OrganizationId], [Office])
GO
ALTER TABLE [dbo].[Office] ADD CONSTRAINT [FK_Office_Node] FOREIGN KEY ([NodeId]) REFERENCES [dbo].[Node] ([NodeId])
GO
ALTER TABLE [dbo].[Office] ADD CONSTRAINT [FK_Office_Office] FOREIGN KEY ([RootOfficeId]) REFERENCES [dbo].[Office] ([OfficeId])
GO
ALTER TABLE [dbo].[Office] ADD CONSTRAINT [FK_Office_Office1] FOREIGN KEY ([ParentOfficeId]) REFERENCES [dbo].[Office] ([OfficeId])
GO
ALTER TABLE [dbo].[Office] ADD CONSTRAINT [FK_Office_Office2] FOREIGN KEY ([BackOfficeId]) REFERENCES [dbo].[Office] ([OfficeId])
GO
ALTER TABLE [dbo].[Office] ADD CONSTRAINT [FK_Office_TenantOrganization] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[TenantOrganization] ([OrganizationId])
GO
EXEC sp_addextendedproperty N'Description', N'samar
07/11/2017

This table will have the list of office (logical or phycial, cost centers, site location) for TenantOrganization', 'SCHEMA', N'dbo', 'TABLE', N'Office', NULL, NULL
GO
