/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[OptionPropertyHistoryLog]
(
[OptionPropertyId] [int] NOT NULL,
[OptionId] [int] NOT NULL,
[OptionProperty] [varchar] (100) NOT NULL,
[EntityListItemId] [int] NOT NULL,
[DataTypeListItemId] [int] NOT NULL,
[ShowInUI] [bit] NOT NULL,
[DefaultValue] [nvarchar] (1000) NOT NULL,
[Source] [nvarchar] (max) NOT NULL,
[TableName] [varchar] (100) NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL,
[Description] [nvarchar] (1000) NOT NULL,
[ColumnName] [varchar] (100) NULL
)
GO
CREATE CLUSTERED INDEX [ix_OptionPropertyHistoryLog] ON [dbo].[OptionPropertyHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[OptionProperty]
(
[OptionPropertyId] [int] NOT NULL IDENTITY(1, 1),
[OptionId] [int] NOT NULL,
[OptionProperty] [varchar] (100) NOT NULL,
[EntityListItemId] [int] NOT NULL,
[DataTypeListItemId] [int] NOT NULL CONSTRAINT [DF_OptionProperty_DataTyleListItemId] DEFAULT ((1)),
[ShowInUI] [bit] NOT NULL CONSTRAINT [DF_OptionProperty_ShowInUI] DEFAULT ((0)),
[DefaultValue] [nvarchar] (1000) NOT NULL,
[Source] [nvarchar] (max) NOT NULL,
[TableName] [varchar] (100) NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_OptionProperty_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFOptionPropertyStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFOptionPropertyEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
[Description] [nvarchar] (1000) NOT NULL CONSTRAINT [DF__OptionPro__Descr__61824303] DEFAULT (''),
[ColumnName] [varchar] (100) NULL,
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_OptionProperty] PRIMARY KEY CLUSTERED ([OptionPropertyId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[OptionPropertyHistoryLog])
)
GO
ALTER TABLE [dbo].[OptionProperty] ADD CONSTRAINT [UkOptionPropertyOptionIdOptionProperty] UNIQUE NONCLUSTERED ([OptionId], [OptionProperty])
GO
ALTER TABLE [dbo].[OptionProperty] ADD CONSTRAINT [FK_OptionProperty_Option] FOREIGN KEY ([OptionId]) REFERENCES [dbo].[Option] ([OptionId])
GO
