/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[OptionHistoryLog]
(
[OptionId] [int] NOT NULL,
[Option] [varchar] (100) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL,
[RelatesTo] [varchar] (1000) NULL
)
GO
CREATE CLUSTERED INDEX [ix_OptionHistoryLog] ON [dbo].[OptionHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[Option]
(
[OptionId] [int] NOT NULL IDENTITY(1, 1),
[Option] [varchar] (100) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_Option_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFOptionStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFOptionEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
[RelatesTo] [varchar] (1000) NULL,
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_Option] PRIMARY KEY CLUSTERED ([OptionId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[OptionHistoryLog])
)
GO
ALTER TABLE [dbo].[Option] ADD CONSTRAINT [UkOptionOption] UNIQUE NONCLUSTERED ([Option])
GO
EXEC sp_addextendedproperty N'MS_Description', N'Purpose of Adding RelatesTo column is to Differentiate the Option that are used while setting up Email profile from ATM app', 'SCHEMA', N'dbo', 'TABLE', N'Option', NULL, NULL
GO
