/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[OrganizationHistoryLog]
(
[OrganizationId] [int] NOT NULL,
[OfficeId] [int] NOT NULL,
[Organization] [nvarchar] (100) NOT NULL,
[Department] [nvarchar] (100) NOT NULL,
[ParentOrganizationId] [int] NULL,
[RootOrganizationId] [int] NULL,
[BackOfficeId] [int] NULL,
[FundingOrganizationId] [int] NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[ReferenceId] [varchar] (50) NULL,
[ReferenceNote] [varchar] (100) NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_OrganizationHistoryLog] ON [dbo].[OrganizationHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[Organization]
(
[OrganizationId] [int] NOT NULL IDENTITY(1, 1),
[OfficeId] [int] NOT NULL,
[Organization] [nvarchar] (100) NOT NULL,
[Department] [nvarchar] (100) NOT NULL,
[ParentOrganizationId] [int] NULL,
[RootOrganizationId] [int] NULL,
[BackOfficeId] [int] NULL,
[FundingOrganizationId] [int] NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_Organization_InsertDate] DEFAULT (getdate()),
[ReferenceId] [varchar] (50) NULL,
[ReferenceNote] [varchar] (100) NULL,
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFOrganizationStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFOrganizationEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_Organization] PRIMARY KEY CLUSTERED ([OrganizationId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[OrganizationHistoryLog])
)
GO
CREATE NONCLUSTERED INDEX [IXOrganizationOfficeId] ON [dbo].[Organization] ([OfficeId])
GO
ALTER TABLE [dbo].[Organization] ADD CONSTRAINT [FK_Organization_Office] FOREIGN KEY ([OfficeId]) REFERENCES [dbo].[Office] ([OfficeId])
GO
ALTER TABLE [dbo].[Organization] ADD CONSTRAINT [FK_Organization_Office1] FOREIGN KEY ([BackOfficeId]) REFERENCES [dbo].[Office] ([OfficeId])
GO
ALTER TABLE [dbo].[Organization] ADD CONSTRAINT [FK_Organization_Organization] FOREIGN KEY ([FundingOrganizationId]) REFERENCES [dbo].[Organization] ([OrganizationId])
GO
EXEC sp_addextendedproperty N'MS_Description', N'OfficeId for Tenant,Organization and TenantOrganization is its main office
OfficeId for Lead,Target,NewCustomer,Customer and Agency is its handling office.
OfficeId is by default handling office.If the organization is only TenantOrganization then it is the default office.
', 'SCHEMA', N'dbo', 'TABLE', N'Organization', NULL, NULL
GO
