/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[OrganizationOptionHistoryLog]
(
[OrganizationOptionId] [int] NOT NULL,
[OrganizationId] [int] NOT NULL,
[OptionPropertyId] [int] NOT NULL,
[OptionValue] [nvarchar] (1000) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_OrganizationOptionHistoryLog] ON [dbo].[OrganizationOptionHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[OrganizationOption]
(
[OrganizationOptionId] [int] NOT NULL IDENTITY(1, 1),
[OrganizationId] [int] NOT NULL,
[OptionPropertyId] [int] NOT NULL,
[OptionValue] [nvarchar] (1000) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_OrganizationOption_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFOrganizationOptionStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFOrganizationOptionEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_OrganizationOption] PRIMARY KEY CLUSTERED ([OrganizationOptionId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[OrganizationOptionHistoryLog])
)
GO
ALTER TABLE [dbo].[OrganizationOption] ADD CONSTRAINT [UkOrganizationOptionOrganizationIdOptionPropertyId] UNIQUE NONCLUSTERED ([OrganizationId], [OptionPropertyId])
GO
ALTER TABLE [dbo].[OrganizationOption] ADD CONSTRAINT [FK_OrganizationOption_OptionProperty] FOREIGN KEY ([OptionPropertyId]) REFERENCES [dbo].[OptionProperty] ([OptionPropertyId])
GO
ALTER TABLE [dbo].[OrganizationOption] ADD CONSTRAINT [FK_OrganizationOption_Organization] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organization] ([OrganizationId])
GO
