/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[PersonOptionHistoryLog]
(
[PersonOptionId] [int] NOT NULL,
[PersonId] [int] NOT NULL,
[OptionPropertyId] [int] NOT NULL,
[OptionValue] [nvarchar] (1000) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_PersonOptionHistoryLog] ON [dbo].[PersonOptionHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[PersonOption]
(
[PersonOptionId] [int] NOT NULL IDENTITY(1, 1),
[PersonId] [int] NOT NULL,
[OptionPropertyId] [int] NOT NULL,
[OptionValue] [nvarchar] (1000) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_PersonOption_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFPersonOptionStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFPersonOptionEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_PersonOption] PRIMARY KEY CLUSTERED ([PersonOptionId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[PersonOptionHistoryLog])
)
GO
ALTER TABLE [dbo].[PersonOption] ADD CONSTRAINT [UkPersonOptionPersonIdOptionPropertyId] UNIQUE NONCLUSTERED ([PersonId], [OptionPropertyId])
GO
ALTER TABLE [dbo].[PersonOption] ADD CONSTRAINT [FK_PersonOption_OptionProperty] FOREIGN KEY ([OptionPropertyId]) REFERENCES [dbo].[OptionProperty] ([OptionPropertyId])
GO
