/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[RoleHistoryLog]
(
[RoleId] [int] NOT NULL,
[Role] [varchar] (25) NOT NULL,
[StatusListItemId] [int] NOT NULL,
[ResourceId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL,
[Description] [varchar] (200) NULL
)
GO
CREATE CLUSTERED INDEX [ix_RoleHistoryLog] ON [dbo].[RoleHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[Role]
(
[RoleId] [int] NOT NULL IDENTITY(1, 1),
[Role] [varchar] (25) NOT NULL,
[StatusListItemId] [int] NOT NULL,
[ResourceId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_Role_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFRoleStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFRoleEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
[Description] [varchar] (200) NULL,
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([RoleId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[RoleHistoryLog])
)
GO
ALTER TABLE [dbo].[Role] ADD CONSTRAINT [UkRoleRole] UNIQUE NONCLUSTERED ([Role])
GO
ALTER TABLE [dbo].[Role] ADD CONSTRAINT [FK_Role_Resource] FOREIGN KEY ([ResourceId]) REFERENCES [dbo].[Resource] ([ResourceId])
GO
