/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[SystemHistoryLog]
(
[SystemId] [int] NOT NULL,
[System] [varchar] (15) NOT NULL,
[Version] [varchar] (25) NOT NULL,
[VersionNumber] [int] NOT NULL,
[Mode] [char] (1) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_SystemHistoryLog] ON [dbo].[SystemHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[System]
(
[SystemId] [int] NOT NULL,
[System] [varchar] (15) NOT NULL,
[Version] [varchar] (25) NOT NULL,
[VersionNumber] [int] NOT NULL,
[Mode] [char] (1) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_System_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFSystemStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFSystemEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_System] PRIMARY KEY CLUSTERED ([SystemId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[SystemHistoryLog])
)
GO
ALTER TABLE [dbo].[System] ADD CONSTRAINT [CK_System_Mode] CHECK (([Mode]='T' OR [Mode]='L'))
GO
ALTER TABLE [dbo].[System] ADD CONSTRAINT [CK_System_PK] CHECK (([SystemId]=(1)))
GO
