/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[SystemOptionHistoryLog]
(
[SystemOptionId] [int] NOT NULL,
[SystemId] [int] NOT NULL,
[OptionPropertyId] [int] NOT NULL,
[OptionValue] [nvarchar] (1000) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_SystemOptionHistoryLog] ON [dbo].[SystemOptionHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[SystemOption]
(
[SystemOptionId] [int] NOT NULL IDENTITY(1, 1),
[SystemId] [int] NOT NULL,
[OptionPropertyId] [int] NOT NULL,
[OptionValue] [nvarchar] (1000) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_SystemOption_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFSystemOptionStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFSystemOptionEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_SystemOption] PRIMARY KEY CLUSTERED ([SystemOptionId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[SystemOptionHistoryLog])
)
GO
ALTER TABLE [dbo].[SystemOption] ADD CONSTRAINT [UkSystemOptionSystemIdOptionPropertyId] UNIQUE NONCLUSTERED ([SystemId], [OptionPropertyId])
GO
ALTER TABLE [dbo].[SystemOption] ADD CONSTRAINT [FK_SystemOption_OptionProperty] FOREIGN KEY ([OptionPropertyId]) REFERENCES [dbo].[OptionProperty] ([OptionPropertyId])
GO
ALTER TABLE [dbo].[SystemOption] ADD CONSTRAINT [FK_SystemOption_System] FOREIGN KEY ([SystemId]) REFERENCES [dbo].[System] ([SystemId])
GO
