/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[TenantOrganizationHistoryLog]
(
[OrganizationId] [int] NOT NULL,
[TenantId] [int] NOT NULL,
[OfficeId] [int] NULL,
[Alias] [varchar] (15) NOT NULL,
[DBA] [nvarchar] (100) NULL,
[FEIN] [varchar] (25) NULL,
[NodeId] [int] NOT NULL,
[StatusListItemId] [int] NOT NULL,
[GLCode] [varchar] (25) NOT NULL,
[ServiceTypeListItemId] [int] NOT NULL,
[NextInvoiceNumber] [int] NOT NULL,
[CompanyProfile] [varchar] (max) NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[ReferenceId] [varchar] (50) NULL,
[ReferenceNote] [varchar] (100) NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_TenantOrganizationHistoryLog] ON [dbo].[TenantOrganizationHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[TenantOrganization]
(
[OrganizationId] [int] NOT NULL,
[TenantId] [int] NOT NULL,
[OfficeId] [int] NULL,
[Alias] [varchar] (15) NOT NULL,
[DBA] [nvarchar] (100) NULL,
[FEIN] [varchar] (25) NULL,
[NodeId] [int] NOT NULL,
[StatusListItemId] [int] NOT NULL,
[GLCode] [varchar] (25) NOT NULL CONSTRAINT [DF_TenantOrganization_GLCode] DEFAULT ('000'),
[ServiceTypeListItemId] [int] NOT NULL CONSTRAINT [DF_TenantOrganization_ServiceTypeListItemId] DEFAULT ((0)),
[NextInvoiceNumber] [int] NOT NULL,
[CompanyProfile] [varchar] (max) NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_TenantOrganization_InsertDate] DEFAULT (getdate()),
[ReferenceId] [varchar] (50) NULL,
[ReferenceNote] [varchar] (100) NULL,
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFTenantOrganizationStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFTenantOrganizationEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_TenantOrganization] PRIMARY KEY CLUSTERED ([OrganizationId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[TenantOrganizationHistoryLog])
)
GO
ALTER TABLE [dbo].[TenantOrganization] ADD CONSTRAINT [UkTenantOrganizationAlias] UNIQUE NONCLUSTERED ([Alias])
GO
ALTER TABLE [dbo].[TenantOrganization] ADD CONSTRAINT [FK_TenantOrganization_Node] FOREIGN KEY ([NodeId]) REFERENCES [dbo].[Node] ([NodeId])
GO
ALTER TABLE [dbo].[TenantOrganization] ADD CONSTRAINT [FK_TenantOrganization_Office] FOREIGN KEY ([OfficeId]) REFERENCES [dbo].[Office] ([OfficeId])
GO
ALTER TABLE [dbo].[TenantOrganization] ADD CONSTRAINT [FK_TenantOrganization_Organization] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organization] ([OrganizationId])
GO
ALTER TABLE [dbo].[TenantOrganization] ADD CONSTRAINT [FK_TenantOrganization_Tenant] FOREIGN KEY ([TenantId]) REFERENCES [dbo].[Tenant] ([TenantId])
GO
EXEC sp_addextendedproperty N'MS_Description', N'TenantOrganization are the actual organization that uses the system. Staffing Companies, Corporate HR, Recruiter Agency, PEO, ASO, HRO will be in this table.
OfficeId is default office of the TenantOrganization', 'SCHEMA', N'dbo', 'TABLE', N'TenantOrganization', NULL, NULL
GO
