/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[TenantOptionHistoryLog]
(
[TenantOptionId] [int] NOT NULL,
[TenantId] [int] NOT NULL,
[OptionPropertyId] [int] NOT NULL,
[OptionValue] [nvarchar] (1000) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_TenantOptionHistoryLog] ON [dbo].[TenantOptionHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[TenantOption]
(
[TenantOptionId] [int] NOT NULL IDENTITY(1, 1),
[TenantId] [int] NOT NULL,
[OptionPropertyId] [int] NOT NULL,
[OptionValue] [nvarchar] (1000) NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_TenantOption_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFTenantOptionStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFTenantOptionEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_TenantOption] PRIMARY KEY CLUSTERED ([TenantOptionId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[TenantOptionHistoryLog])
)
GO
ALTER TABLE [dbo].[TenantOption] ADD CONSTRAINT [UkTenantOptionTenantIdOptionPropertyId] UNIQUE NONCLUSTERED ([TenantId], [OptionPropertyId])
GO
ALTER TABLE [dbo].[TenantOption] ADD CONSTRAINT [FK_TenantOption_OptionProperty] FOREIGN KEY ([OptionPropertyId]) REFERENCES [dbo].[OptionProperty] ([OptionPropertyId])
GO
ALTER TABLE [dbo].[TenantOption] ADD CONSTRAINT [FK_TenantOption_Tenant] FOREIGN KEY ([TenantId]) REFERENCES [dbo].[Tenant] ([TenantId])
GO
