/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[TenantHistoryLog]
(
[TenantId] [int] NOT NULL,
[SystemId] [int] NOT NULL,
[Tenant] [nvarchar] (100) NOT NULL,
[TenantTypeListItemId] [int] NULL,
[OrganizationId] [int] NOT NULL,
[NodeId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL,
[StartPeriod] [datetime2] NOT NULL,
[EndPeriod] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_TenantHistoryLog] ON [dbo].[TenantHistoryLog] ([EndPeriod], [StartPeriod])
GO
CREATE TABLE [dbo].[Tenant]
(
[TenantId] [int] NOT NULL IDENTITY(1, 1),
[SystemId] [int] NOT NULL,
[Tenant] [nvarchar] (100) NOT NULL,
[TenantTypeListItemId] [int] NULL,
[OrganizationId] [int] NOT NULL,
[NodeId] [int] NOT NULL,
[UserPersonId] [int] NOT NULL,
[InsertDate] [smalldatetime] NOT NULL CONSTRAINT [DF_Tenant_InsertDate] DEFAULT (getdate()),
[StartPeriod] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DFTenantStartPeriod] DEFAULT (sysutcdatetime()),
[EndPeriod] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DFTenantEndPeriod] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
PERIOD FOR SYSTEM_TIME (StartPeriod, EndPeriod),
CONSTRAINT [PK_Tenant] PRIMARY KEY CLUSTERED ([TenantId])
)
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[TenantHistoryLog])
)
GO
ALTER TABLE [dbo].[Tenant] ADD CONSTRAINT [UkTenantTenant] UNIQUE NONCLUSTERED ([Tenant])
GO
ALTER TABLE [dbo].[Tenant] ADD CONSTRAINT [FK_Tenant_Node] FOREIGN KEY ([NodeId]) REFERENCES [dbo].[Node] ([NodeId])
GO
ALTER TABLE [dbo].[Tenant] ADD CONSTRAINT [FK_Tenant_System] FOREIGN KEY ([SystemId]) REFERENCES [dbo].[System] ([SystemId])
GO
ALTER TABLE [dbo].[Tenant] ADD CONSTRAINT [FK_Tenant_TenantOrganization] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[TenantOrganization] ([OrganizationId])
GO
