/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[PERSON]
(
[PERSONID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [varchar] (50) NULL
)
GO
ALTER TABLE [dbo].[PERSON] ADD CONSTRAINT [PK__PERSON__0986239EECA59E69] PRIMARY KEY CLUSTERED ([PERSONID])
GO
